### ISSUE TITLE
Kitchen Converge without attempting to create a new VM

### ISSUE THREAD

**Issue by james-s-nduka** [CenturyLinkCloud/chef-provisioning-vsphere#113]
I am using the kitchen features of this gem and I'd like to run _kitchen converge_ on an existing VM and not **create** a new VM (as I do not have privileges to do so)

What options would I need to pass in my .kitchen.yml to achieve this? 

Here is a snippet of it;
```
---
driver:
  name: vsphere
  driver_options:
    host: 'VMHOSTUK.UKROI.EXAMPLE.ORG'
    user: 'user'
    password: 'passwd'
    insecure: true
  machine_options:
    bootstrap_options:
      use_linked_clone: true
      datacenter: 'STORE-DATACENTER'
      template_name: 'UK09125ISS03'
      template_folder: 'UK09125-VM'
      resource_pool: 'UK09125-CLU'
      ssh:
        user: 'user'
        paranoid: false
        password: 'passwd'
        port: 5985

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: UK09125ISS03
    transport:
      name: winrm
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[configure_and_format_disk::default]
```

```template_name: 'UK09125ISS03'``` is a powered on VM and not a template

Here is the exception I am getting;
`>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [NoPermission: Permission to perform this operation was denied.] on default-UK09125ISS03
>>>>>> ----------------------`
