### ISSUE TITLE
Kitchen VM creates and works until the IP change is attemped

### ISSUE THREAD

**Issue by gleg** [CenturyLinkCloud/chef-provisioning-vsphere#29]
I've watched the process, the VM starts and works but has the template IP. It then reboots and attempts to change the IP and won't start with an error stating that it could not parse or process the unattend file. The machine is then just stuck on a loop where it reboots with an error stating that there was a problem with the installation. If I use regedit to change the following value HKLocal machine/SYSTEM/SETUP/STATUS/ChildCompletion/setup.exe to 3 it will boot with everything working fine including the IP.

The unattend.xml before IP change and after is the same except for the mac address. Can you actually set an IP in the kitchen.yml file? It works fine if you leave the IP alone but this leaves my testing limited to one VM at a time unless I have loads of templates.

My config:
```
---
driver_plugin: vsphere
driver_config:
  driver_options:
    host: 'vcentre.host.net'
    user: 'gwhiting'
    password: 'password'
    insecure: true
  machine_options:
    start_timeout: 600
    create_timeout: 600
    ready_timeout: 600
    bootstrap_options:
      use_linked_clone: true
      template_name: 'vsphere-test'
      template_folder: 'Ops Test Lab/Gregs Sandbox/'
      vm_folder: 'Ops Test Lab/Gregs Sandbox/'
      datacenter: 'GS-Datacenter'
      num_cpus: 2,
      network_name:
        - VLAN-36
      memory_mb: 4096
      resource_pool: pex-vmware07.host.net
      datastore: v7000-vmware-uat12
      ssh:
        user: Administrator
        paranoid: false
        password: 'adminpw'
        port: 22
      convergence_options:
      customization_spec:
        ipsettings:
          ip: '10.128.36.186'
          subnetMask: '255.255.255.0'
          gateway:
            - 10.128.36.1
          dnsServerList:
              - 172.16.36.121
              - 172.16.36.123
        domain: my_domain.local
        domainAdmin: administrator@my_domain.local
        domainAdminPassword: my_password
        org_name: my_org
        product_id: 11111-22222-33333-44444-55555
        win_time_zone: 4
          
provisioner:
  name: chef_zero

platforms:
  - name: WindowsServer2012R2x64v1_2
    transport: 
      name: winrm
    driver:
       guest: windows

suites:
  - name: default
    run_list:
      - recipe[bg-chocolatey::default]
```
