### ISSUE TITLE
ssh key support?

### ISSUE THREAD

**Issue by mrmarbury** [CenturyLinkCloud/chef-provisioning-vsphere#46]
Hi,

for our testing we need the user that provisions the VM to have an SSH key. Somehow I am not able to find any useful information on this when doing a google search. Is there an option to provide the ssh key?

Cheers,
Stefan

**Comment by mwrock** [comment]
Under `[:bootstrap_options][:ssh]` you could try adding a `:keys` and pass it the key file in an array: `[ '~/some/key']`

The config options under `[:ssh]` just get forwarded to ruby's `Net::SSH.start`

**Comment by mrmarbury** [comment]
Hi,

thx for the answer. Unfortunately I cannot get it to work. The ssh portion of my kitchen yaml looks as follows:

```  
bootstrap_options:      
  ssh:
    user: chefinit
    paranoid: false
    port: 22
    keys:
      - ~/.ssh/id_rsa_chef
```
I can do a manual login with this key at this VM which works fine.
