### ISSUE TITLE
Network Does not Connect on Power-on

### ISSUE THREAD

**Issue by airom** [CenturyLinkCloud/chef-provisioning-vsphere#63]
Hi,

I  have an issue that when when i provision an instance using test-kitchen, the instance gets created but the network is not connection. So if i login ad enable the "connect on Power on" and "Connect" the converge continues and works. 
I use vmware vCenter 6 and ESXi 6.

here is my .kitchen.yml:

```
---
driver_plugin: vsphere
driver_config:
  driver_options:
    host: <%= ENV['VMWARE_HOST'] %>
    user: <%= ENV['VMWARE_USER'] %>
    password: <%= ENV['VMWARE_PASS'] %>
    insecure: true
  machine_options:
    start_timeout: 600
    create_timeout: 600
    ready_timeout: 90
    bootstrap_options:
      use_linked_clone: true
      datacenter: 'MyDATACENTER'
      template_name: 'UBUNTU14'
      template_folder: 'Templates'
      vm_folder: 'TEST'
      num_cpus: 2
      network_name: ["vlan12345"]
      memory_mb: 4096
      resource_pool: 'MyVMCluster'
      ssh:
        user: someuser
        paranoid: false
        password: somepassword
        port: 22
      convergence_options:
      customization_spec:
        domain: somedonain.loc
        ipsettings:
          dnsServerList:
            - 8.8.8.8
            - 8.8.4.4

provisioner:
  name: chef_zero
  cookbooks_path: "test/fixtures/cookbooks"
  environments_path: "test/fixtures/environments"
  client_rb:
      environment: cheftest

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[some_cookbook::recipe]
    attributes:
```

And here is the kitchen output:

```
$ kitchen converge -l debug
-----> Starting Kitchen (v1.5.0)
D      Berksfile found at /Users/MYUSER/source/some_cookbook/Berksfile, loading Berkshelf
D      Berkshelf 4.2.1 library loaded
D      Berksfile found at /Users/SOMEUSER/source/some_cookbook/Berksfile, loading Berkshelf
D      Berkshelf 4.2.1 previously loaded
-----> Creating <oracle-8-ubuntu-1404>...
[2016-03-22T17:37:46-07:00] WARN: No cookbooks directory found at or above current directory.  Assuming /Users/SOMEUSER/source/some_cookbook.
creating machine default-ubuntu-1404-55c7f3f3 on vsphere://MYVCENTER/sdk?use_ssl=true&insecure=true
  use_linked_clone: true
  datacenter: "MyDATACENTER"
  template_name: "UBUNTU14"
  template_folder: "Templates"
  vm_folder: "TEST"
  num_cpus: 2
  network_name: ["vlan12345"]
  memory_mb: 4096
  resource_pool: "MyVMCluster"
  ssh: {:user=>"some_user", :paranoid=>false, :password=>"some_password", :port=>22}
  convergence_options: nil
  customization_spec: {:domain=>"somedomain.loc", :ipsettings=>{:dnsServerList=>["8.8.8.8", "8.8.4.4"]}}
establishing connection to MYVCENTER
[2016-03-22T17:37:46-07:00] WARN: Using a VM Template, ignoring use_linked_clone.
finding networks...
network: vlan12345 is a Network
changing template nic for vlan12345
customizing default-ubuntu-1404-55c7f3f3 with /
              dynamic IP and DNS: ["8.8.8.8", "8.8.4.4"]
 Machine - created - oracle-8-ubuntu-1404-55c7f3f3 (50198e29-e440-caa5-5f64-70ade3a070c6 on vsphere://MYVCENTER/sdk?use_ssl=true&insecure=true)
Power on VM [TEST/default-ubuntu-1404-55c7f3f3]
waiting for default-ubuntu-1404-55c7f3f3 (50198e29-e440-caa5-5f64-70ade3a070c6 on vsphere://MYVCENTER/sdk?use_ssl=true&insecure=true) to be ready ...
.........................................................................................
```

At this point, it is just waiting for the VM to get networking. When i check VMWare instance i do not see the network is connected :
![image](https://cloud.githubusercontent.com/assets/5771524/13972512/a712933e-f056-11e5-9be1-d53e3b721020.png)

Any thoughts ?
My goal is to use vsphere for Kitchen to spin up instances and run the test and destroy afterward.
