### ISSUE TITLE
Running kitchen create multiple times creates multiple VMs

### ISSUE THREAD

**Issue by k0dk0d** [CenturyLinkCloud/chef-provisioning-vsphere#7]
Ahoy hoy,

I've recently switched from the now discontinued kitchen-vsphere driver to this one and came across an issue today: If you run `kitchen create` multiple times, it clones a new VM every time, leaving the one created before in a state that is no longer manageable with testkitchen commandline tools. You need to login to the vSphere Client and shutdown/delete the previously created machines by hand.

I originally stumbled across it because I changed the "memory_mb" and wondered if it would change the allocated memory on an already created machine. I then tested it with no changes to the .kitchen.yml, but it still creates a new VM every time I run `kitchen create`.

Here is my (redacted) .kitchen.yml:
```yaml
---
driver_plugin: vsphere
driver_config:
  driver_options:
    host: ***
    user: ***
    password: ***
    insecure: true
  machine_options:
    start_timeout: 600
    create_timeout: 600
    ready_timeout: 90
    bootstrap_options:
      datacenter: ***
      resource_pool: 'Test'
      template_folder: 'Test/Chef-Testumgebung/Testkitchen/Templates'
      vm_folder: 'Test/Chef-Testumgebung/Testkitchen'
      memory_mb: 2048
      ssh:
        user: ***
        password: ***
        paranoid: false

provisioner:
  name: chef_zero

platforms:
  - name: sles11
    driver_config:
      machine_options:
        bootstrap_options:
          template_name: 'testkitchen-sles11-chef11-minimal'
```

Steps to reproduce: Use the testkitchen driver as described [here](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere#kitchen-driver) and run `kitchen create` twice without running `kitchen destroy` in between.
